### ISSUE TITLE
When i use create_dataset_2.py i have a error

### ISSUE THREAD

**Issue by 17702513221** [GajuuzZ/Human-Falling-Detect-Tracks#10]
I do not have test.txt in Annotation_files
Data/falldata/Home/Annotation_files/test.txt
Can you give me dataset

**Comment by 17702513221** [comment]
Can you tell me how to prepare txt

**Comment by 17702513221** [comment]
Can i use https://github.com/open-mmlab/mmskeleton train st-gcn model

**Comment by 17702513221** [comment]
@GajuuzZ

**Comment by xwr96** [comment]
> Can you tell me how to prepare txt

do you know how to prepare the .txt? I confuse with it
