### ISSUE TITLE
what should i do to make my own dataset

### ISSUE THREAD

**Issue by xwr96** [GajuuzZ/Human-Falling-Detect-Tracks#14]
Hi! becasue the dataset link http://le2i.cnrs.fr/Fall-detection-Dataset?lang=en is death, so how to make my own dataset? I will appreciate u if you can give me some advice.

**Comment by GajuuzZ** [comment]
https://github.com/GajuuzZ/Human-Falling-Detect-Tracks/issues/2#issuecomment-617718127
