### ISSUE TITLE
Can you give me some datas to train st-gcn?

### ISSUE THREAD

**Issue by Nono17** [GajuuzZ/Human-Falling-Detect-Tracks#2]
I want the data to train st-gcn,such as
'../Data/Coffee_room_new-set(labelXscrw).pkl',
'../Data/Home_new-set(labelXscrw).pkl'
Can you share your data with me.
I don't know how to mark it, or can I have a look at your file data template.
Thanks very much.
If ok ,please send me an email to xudw@deepblueai.com.

**Comment by GajuuzZ** [comment]
The data set is from http://le2i.cnrs.fr/Fall-detection-Dataset?lang=en but i think the download link is dead now. I wrote the script to create that data files but it quite in a manual way and specific on the data set so I didn't upload them. If you want to create your own data set you need to use the Pose model to extract the joints position (x, y, score) from each frame do some normalization and label them frame by frame then store them in a sequence of array. I wrote a comment about the inputs shape in Actionsrecognition/train.py If you have any questions you can ask.

**Comment by PoroWang** [comment]
Hi, first i want to thanks for providing this repo. I'm doing a similar project about skeleton-based action recognition.
I was trying to train my own datasets on st-gcn, too, but i have no idea how to convert my data to proper .pkl or .npy file to fit the training scripts.
I saw the comment in Actionsrecognition/train.py:
"Default data create from: Data.create_dataset_(1-3).py"
Are these scripts using for create the data files? If so, hoping you can provide them.
I know it is only for specific dataset, but i think if there is any example it would be easy to write my own scripts.
I will appreciate for your help.
My email: s108062502@m108.nthu.edu.tw

**Comment by GajuuzZ** [comment]
I have provided create_dataset_(1-3).py files in the Data folder.

**Comment by PoroWang** [comment]
Thank you!
I will keep trying on my work!

**Comment by 17702513221** [comment]
Can you help me how to prepare txt in create_dataset_2 @Nono17  @GajuuzZ

**Comment by wxk2008** [comment]
> Thank you!
> I will keep trying on my work!

can you train your own model in success？

**Comment by sxy-926** [comment]
Hi, first i want to thanks for providing this repo.I was trying to train my own datasets on st-gcn, but i have no idea how to convert my data to proper .pkl or .npy file to fit the training scripts.I have got Data.create_dataset_（1-3）.py.
But I don’t know what format the txt file should be in "annot_folder ='../Data/Annotation_files' # bounding box annotation for each frame."  .Can you send me a copy of your data set? Let me make a reference, thank you very much!
It will be very helpful to me

**Comment by Sukeysun** [comment]
> Hi, first i want to thanks for providing this repo.I was trying to train my own datasets on st-gcn, but i have no idea how to convert my data to proper .pkl or .npy file to fit the training scripts.I have got Data.create_dataset_（1-3）.py.
> But I don’t know what format the txt file should be in "annot_folder ='../Data/Annotation_files' # bounding box annotation for each frame." .Can you send me a copy of your data set? Let me make a reference, thank you very much!
> It will be very helpful to me.
> If ok ,please send me an email to [15776554620@163.com](mailto:15776554620@163.com).

Hi, have you known what the format of the txt file should be ?  Would let me know how to make it?

**Comment by sxy-926** [comment]
> > Hi, first i want to thanks for providing this repo.I was trying to train my own datasets on st-gcn, but i have no idea how to convert my data to proper .pkl or .npy file to fit the training scripts.I have got Data.create_dataset_（1-3）.py.
> > But I don’t know what format the txt file should be in "annot_folder ='../Data/Annotation_files' # bounding box annotation for each frame." .Can you send me a copy of your data set? Let me make a reference, thank you very much!
> > It will be very helpful to me.
> > If ok ,please send me an email to [15776554620@163.com](mailto:15776554620@163.com).
> 
> Hi, have you known what the format of the txt file should be ? Would let me know how to make it?

I got it. This txt file contains a bbox of the area where the action occurs in the video.
for example:

frame   label       x                                         y                                        w                                 h
32          0           0.5847656250000001     0.5048611111111111         0.11640625             0.47361111111111115

**Comment by Malithi-gif** [comment]
@sxy-926 Can you send me the annotation file?

@GajuuzZ, How to create own annotation file?

**Comment by Malithi-gif** [comment]
> > > Hi, first i want to thanks for providing this repo.I was trying to train my own datasets on st-gcn, but i have no idea how to convert my data to proper .pkl or .npy file to fit the training scripts.I have got Data.create_dataset_（1-3）.py.
> > > But I don’t know what format the txt file should be in "annot_folder ='../Data/Annotation_files' # bounding box annotation for each frame." .Can you send me a copy of your data set? Let me make a reference, thank you very much!
> > > It will be very helpful to me.
> > > If ok ,please send me an email to [15776554620@163.com](mailto:15776554620@163.com).
> > 
> > 
> > Hi, have you known what the format of the txt file should be ? Would let me know how to make it?
> 
> I got it. This txt file contains a bbox of the area where the action occurs in the video.
> for example:
> 
> frame label x y w h
> 32 0 0.5847656250000001 0.5048611111111111 0.11640625 0.47361111111111115

Hi, How you created annotation files. Thank youu..

**Comment by shiyajing111** [comment]
> > > Hi, first i want to thanks for providing this repo.I was trying to train my own datasets on st-gcn, but i have no idea how to convert my data to proper .pkl or .npy file to fit the training scripts.I have got Data.create_dataset_（1-3）.py.
> > > But I don’t know what format the txt file should be in "annot_folder ='../Data/Annotation_files' # bounding box annotation for each frame." .Can you send me a copy of your data set? Let me make a reference, thank you very much!
> > > It will be very helpful to me.
> > > If ok ,please send me an email to [15776554620@163.com](mailto:15776554620@163.com).
> > 
> > 
> > Hi, have you known what the format of the txt file should be ? Would let me know how to make it?
> 
> I got it. This txt file contains a bbox of the area where the action occurs in the video.
> for example:
> 
> frame label x y w h
> 32 0 0.5847656250000001 0.5048611111111111 0.11640625 0.47361111111111115

Can you send me the annotation file?Thank you！！546767959@qq.com

**Comment by maocaixia** [comment]
> I have provided create_dataset_(1-3).py files in the Data folder.

Hello, when I run create_dataset_3.py, it's so slow with 2000 fall videos, is it normal or maybe is there some problems?

**Comment by RickChou** [comment]
> > I have provided create_dataset_(1-3).py files in the Data folder.
> 
> Hello, when I run create_dataset_3.py, it's so slow with 2000 fall videos, is it normal or maybe is there some problems? Thanks a lot! @GajuuzZ

May I ask how to use create_dataset_1.py to create Home_new, the labels I get using create_dataset_1.py are all 0

**Comment by sard0r** [comment]
@RickChou @GajuuzZ  Did you solve this problem? I am facing the same issue when I run the create_dataset_1.py. if you have solved the problem can you provide your opinion?
