### ISSUE TITLE
weight file

### ISSUE THREAD

**Issue by xwr96** [GajuuzZ/Human-Falling-Detect-Tracks#20]
HI!
I want to ask that is the fast_res50_256x192.pth weight file is trained by alphapose? tsstg-model.pth trained by st-gcn or mmskeleton,  best_ model.pth weight file trained by Yolov3? because I want to train my own weight file,thanks!

**Comment by GajuuzZ** [comment]
Tiny-YOLO oneclass - .pth, .cfg
SPPE FastPose (AlphaPose) - resnet101, resnet50
ST-GCN action recognition - tsstg

**Comment by xwr96** [comment]
another question.
I saw the create_dataset_2.py in your Data folder, I confused with code below:
`annot_folder = '../Data/falldata/Home/Annotation_files'  # bounding box annotation for each frame`
I think this is the xx.txt file, so how can i produce this txt file? can u give me some advice?

**Comment by GajuuzZ** [comment]
It's a text file that contains the Bounding Box position of the person for each frame.

**Comment by xwr96** [comment]
what is the format of Bounding Box position in the text file? is (frames, x, y, w, h) or something else?  (x,y) is the center point coordinates of every frame. 
Looking forward to your reply. thanks
