### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by dengxuankun** [GajuuzZ/Human-Falling-Detect-Tracks#25]
when I load yoloV3 ,I meet this error:
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
 I have tried torch 1.4 1.5 and 1.6 ,  but have same error,
can you give me some help. thank you

**Comment by GengCauWong** [comment]
> when I load yoloV3 ,I meet this error:
> magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, 'v'.
> I have tried torch 1.4 1.5 and 1.6 , but have same error,
> can you give me some help. thank you

请问这个问题您是怎么解决的呢？

**Comment by mabaisen** [comment]
请问您解决了吗
