### ISSUE TITLE
sequential action frames training in create_dataset_3.py

### ISSUE THREAD

**Issue by haileykwak** [GajuuzZ/Human-Falling-Detect-Tracks#29]
Hi GajuuzZ, Im really appreciated for your dataset code.
I have a question about seq_label_smoothing code.

Can I understand that sequentual action frames influence model training??
For example, if I want to train about the fight action, it will be trained action frames from before to after the fists are stretched?

Thank you for your replying in advance.

**Comment by GajuuzZ** [comment]
It will force the model to predict each input time frames window (30 frame) in the video with probability of each action class. For example when standing up it should be like a 50% of standing and 50% of sitting. So I can use these probability to trigger some threshold.
