### ISSUE TITLE
Hi, I got problems in running train.py (about data_files)

### ISSUE THREAD

**Issue by Zhengkh** [GajuuzZ/Human-Falling-Detect-Tracks#30]
First thank you for your sharing. I got questions in running train.py. 
data_files = ['../Data/Coffee_room_new-set(labelXscrw).pkl',
              '../Data/Home_new-set(labelXscrw).pkl']
I'm wondering what's the difference between the two pkl files. What the 'Coffee' means? Are the two pkl file create from one video or from different videos?
I can already run 1-3 create_dataset code.
I'm really appreciate if you can give me some advice on running train.py.

**Comment by Malithi-gif** [comment]
@Zhengkh did you slove the question?

**Comment by GajuuzZ** [comment]
The name Coffee and Home is just where that dataset was recorded. The dataset is from multiple videos in the same room.

**Comment by Zhengkh** [comment]
> The name Coffee and Home is just where that dataset was recorded. The dataset is from multiple videos in the same room.

Thanks. I've already figured it out.

**Comment by RickChou** [comment]
> First thank you for your sharing. I got questions in running train.py. data_files = ['../Data/Coffee_room_new-set(labelXscrw).pkl', '../Data/Home_new-set(labelXscrw).pkl'] I'm wondering what's the difference between the two pkl files. What the 'Coffee' means? Are the two pkl file create from one video or from different videos? I can already run 1-3 create_dataset code. I'm really appreciate if you can give me some advice on running train.py.

May I ask how to use create_dataset_1.py to create Home_new, the labels I get using create_dataset_1.py are all 0

**Comment by Blueyao17** [comment]
> > First thank you for your sharing. I got questions in running train.py. data_files = ['../Data/Coffee_room_new-set(labelXscrw).pkl', '../Data/Home_new-set(labelXscrw).pkl'] I'm wondering what's the difference between the two pkl files. What the 'Coffee' means? Are the two pkl file create from one video or from different videos? I can already run 1-3 create_dataset code. I'm really appreciate if you can give me some advice on running train.py.
> 
> May I ask how to use create_dataset_1.py to create Home_new, the labels I get using create_dataset_1.py are all 0

Have you solved it?
