### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by shiyajing111** [GajuuzZ/Human-Falling-Detect-Tracks#33]
When I run the train.py file, I get such an error. How can I solve it?

**Comment by GajuuzZ** [comment]
See your error line code and do a debugging not every code will run perfectly on every machines due to different setup. So it nesessary to read the details of your error and do a debugging if you want to be a programmer.

**Comment by Ada1223** [comment]
> When I run the train.py file, I get such an error. How can I solve it?
1.ValueError: num_samples should be a positive integer value, but got num_samples=0
我在训练train.Py文件时先是遇见了这个问题:ValueError: num_samples should be a positive integer value, but got num_samples=0
然后为修改了第68和63行的train_loader = data.DataLoader(train_set, batch_size, shuffle=True)，将true改为false
2.Traceback (most recent call last):
  File "train.py", line 91, in <module>
    valid_loader, train_loader_ = load_dataset(data_files[1:2], batch_size, 0.2)
  File "train.py", line 53, in load_dataset
    features = np.concatenate(features, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
然后我就遇到了上面这个错误
有人能帮忙看看吗?不胜感激!
Have you solve this problem？I met the same error.
