### ISSUE TITLE
../Data/Coffee_room_new-set(labelXscrw).pkl', '../Data/Home_new-set(labelXscrw).pkl

### ISSUE THREAD

**Issue by shiyajing111** [GajuuzZ/Human-Falling-Detect-Tracks#34]
What's the difference between these two pkl files, please?

**Comment by MaarufB** [comment]
I wanna know that too.

**Comment by GajuuzZ** [comment]
https://github.com/GajuuzZ/Human-Falling-Detect-Tracks/issues/30#issuecomment-813037725
