### ISSUE TITLE
i can't run the program

### ISSUE THREAD

**Issue by cscwilson** [GajuuzZ/Human-Falling-Detect-Tracks#36]
HI , 
  sorry that i am first time to try on , I want to test your program using " python main.py $office_demo.avi " but it can't to run and showing below:
usage: main.py [-h] [-C CAMERA] [--detection_input_size DETECTION_INPUT_SIZE]
               [--pose_input_size POSE_INPUT_SIZE]
               [--pose_backbone POSE_BACKBONE] [--show_detected]
               [--show_skeleton] [--save_out SAVE_OUT] [--device DEVICE]
main.py: error: unrecognized arguments: .avi

could you guide me how to ? Thanks!

Wilson

**Comment by cscwilson** [comment]
Because of it only support IP Cam

**Comment by GajuuzZ** [comment]
Your command syntax is wrong, Boy
