### ISSUE TITLE
How did you train the detection model yolov3-tiny？

### ISSUE THREAD

**Issue by zt1112** [GajuuzZ/Human-Falling-Detect-Tracks#40]
The official  yolov3-tiny trained on coco dataset often fails to detect people who fall, so I want to know how you trained？Any data augmentation method？Thanks！

**Comment by GajuuzZ** [comment]
Yes, the smaller model usually has a trade-off on speed and accuracy in this project I need more speed and an inexpensive model. So I use the predicted bounding box from tracking to help the detection of the next frames before feeding into the pose model.
I created this repository to give an idea of how to integrate these models for an application. So you can use other related modules that better to combine instead. 
Anyway, I had trained the Yolo with a traditional method as the original does just with more rotation. But with the simpleness of the tiny model may not handle the data.
