### ISSUE TITLE
Can't recognized  or detect using webcamera

### ISSUE THREAD

**Issue by MaarufB** [GajuuzZ/Human-Falling-Detect-Tracks#45]
Hi thanks for this wonderful repo, I have a problem when using web camera. Upon running ' python main.py -C 0 ' there are no bounding boxes displayed or it doesn't detect. How can I fix it? Thanks in advance

**Comment by GajuuzZ** [comment]
Can you show me the result?

**Comment by MaarufB** [comment]
It's now okay sir. Thanks by the way for this wonderful project.

**Comment by MaarufB** [comment]
> Can you show me the result?

Hi sir How can I use the --save_out parser? It can generate a video but it cant be played
