### ISSUE TITLE
How to train my own action recognition models？

### ISSUE THREAD

**Issue by Brianxq** [GajuuzZ/Human-Falling-Detect-Tracks#5]

**Comment by xwr96** [comment]
@Brianxq 你好！你也在跑这个代码吗？能交流下吗？

**Comment by GajuuzZ** [comment]
https://github.com/GajuuzZ/Human-Falling-Detect-Tracks/issues/2#issuecomment-617718127

**Comment by Zhengkh** [comment]
你好，我关于train.py 有一个问题，前面三个createdataset的程序可以跑通，可以交流一下吗，谢谢

**Comment by GitHubjinliu** [comment]
> 你好，我关于train.py 有一个问题，前面三个createdataset的程序可以跑通，可以交流一下吗，谢谢

方便的话可以加qq 929558605 交流，请备注

**Comment by shiyajing111** [comment]
> _No description provided._

你好，我也想训练自己的数据集，请问可以交流下吗？546767959@qq.com谢谢

**Comment by shiyajing111** [comment]
> 你好，我关于train.py 有一个问题，前面三个createdataset的程序可以跑通，可以交流一下吗，谢谢

你好，我也想训练自己的数据集，可以交流一下吗？546767959@qq.com

**Comment by Easonshow** [comment]
> 你好，我关于train.py 有一个问题，前面三个createdataset的程序可以跑通，可以交流一下吗，谢谢

请问你这个复现流程都完成了吗？可以加QQ一起讨论下吗QQ1014976349

**Comment by hansdom** [comment]
> 你好，我关于train.py 有一个问题，前面三个createdataset的程序可以跑通，可以交流一下吗，谢谢

你好，第二个createdataset程序我跑的时候有错误AssertionError:320 backbone is not support yet!，请问你是怎么解决的？
