### ISSUE TITLE
How can i generate annot_folder(bounding box annotation for each frame.)

### ISSUE THREAD

**Issue by DayDayUpDeng** [GajuuzZ/Human-Falling-Detect-Tracks#50]
dear friend. i want train this stgcn use my own dataset.but i can not use Data/create_dataset_2.py.Beacuse i can not create annot_folder = '../Data/falldata/Home/Annotation_files'  # bounding box annotation for each frame.**My question is how can i create this file. Is Yolo model generated (use Detection/Models)？or i show find other method? if you know.please give me some advices
please. this project is very importent for me.**

**Comment by DayDayUpDeng** [comment]
now i can train my datasets use this code,but the question is result is so bad。when i is falling down。the label still is standing.

**Comment by Tyh19971201** [comment]
> dear friend. i want train this stgcn use my own dataset.but i can not use Data/create_dataset_2.py.Beacuse i can not create annot_folder = '../Data/falldata/Home/Annotation_files' # bounding box annotation for each frame.**My question is how can i create this file. Is Yolo model generated (use Detection/Models)？or i show find other method? if you know.please give me some advices please. this project is very importent for me.**

你好呀，有些问题想请教一下，这是我的qq：1368310075，麻烦加一下哈，或者留一下你的联系方式我加你，非常感谢啦。

**Comment by 15551218648** [comment]
楼主您好，这个文件的问题您解决了吗？可以加个联系方式交流一下吗？这是我的QQ:1295360647

**Comment by DayDayUpDYP** [comment]
我好像解决了，找到了报错的地方修改了一下。但是我不记得咋改的了，如果你需要，我吧代码拷给你。



在 2022-08-02 22:30:27，"7Qzee" ***@***.***> 写道：

楼主您好，这个文件的问题您解决了吗？可以加个联系方式交流一下吗？这是我的QQ:1295360647

**Comment by 15551218648** [comment]
十分需要！真的太感谢你了！



发自我的iPhone


------------------ Original ------------------
From: DayDayUpDeng ***@***.***&gt;
Date: Thu,Aug 4,2022 9:03 AM
To: GajuuzZ/Human-Falling-Detect-Tracks ***@***.***&gt;
Cc: 7Qzee ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [GajuuzZ/Human-Falling-Detect-Tracks] How can i generate annot_folder(bounding box annotation for each frame.) (#50)





 我好像解决了，找到了报错的地方修改了一下。但是我不记得咋改的了，如果你需要，我吧代码拷给你。
 
 
 
 在 2022-08-02 22:30:27，"7Qzee" ***@***.***&gt; 写道：
 
 楼主您好，这个文件的问题您解决了吗？可以加个联系方式交流一下吗？这是我的QQ:1295360647

**Comment by xxxhhhwww** [comment]
> 我好像解决了，找到了报错的地方修改了一下。但是我不记得咋改的了，如果你需要，我吧代码拷给你。 在 2022-08-02 22:30:27，"7Qzee" ***@***.***> 写道： 楼主您好，这个文件的问题您解决了吗？可以加个联系方式交流一下吗？这是我的QQ:1295360647 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>
楼主您好，我也想训练自己的数据，自己调试了很久，执行create_dataset_2.py还是有问题，能加个联系方式交流一下吗？我的qq：1977370475

**Comment by Libra861015** [comment]
您好，方便交流一下嗎，我非常需要
可以用微信嗎，我沒辦法用qq

**Comment by DayDayUpDYP** [comment]
您好，我目前对这块的代码也不熟悉了。一年没碰了。另外，最近一直在秋招，没有打算从事算法方向，所以也不能帮上什么忙。您找其他人试试。不好意思



在 2022-09-28 22:12:06，"Libra861015" ***@***.***> 写道：

您好，方便交流一下嗎，我非常需要
可以用微信嗎，我沒辦法用qq

**Comment by 15551218648** [comment]
您好，再请教一下，如果想训练自己的动作类别，就不是原作者的跌倒检测，这个标签文件
该怎么获取呢？另外stgcn的模型是不是应该重新训练，因为作者提供的预训练模型好像是根据他的跌倒检测训练好的，是不是不能用在其他动作类别上。

发自我的iPhone


------------------ Original ------------------
From: DayDayUpDeng ***@***.***&gt;
Date: Thu,Aug 4,2022 9:03 AM
To: GajuuzZ/Human-Falling-Detect-Tracks ***@***.***&gt;
Cc: 7Qzee ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [GajuuzZ/Human-Falling-Detect-Tracks] How can i generate annot_folder(bounding box annotation for each frame.) (#50)





 我好像解决了，找到了报错的地方修改了一下。但是我不记得咋改的了，如果你需要，我吧代码拷给你。
 
 
 
 在 2022-08-02 22:30:27，"7Qzee" ***@***.***&gt; 写道：
 
 楼主您好，这个文件的问题您解决了吗？可以加个联系方式交流一下吗？这是我的QQ:1295360647
