### ISSUE TITLE
an issue about the input frame number to predict the motion

### ISSUE THREAD

**Issue by FreedoomG** [GajuuzZ/Human-Falling-Detect-Tracks#53]
hi there, it's a nice project
I wonder know can we change the input frame number( default is 30 ) to another number like 20 or 10?
if we can, the length of deque in the Tracker should also be changed to the same number?

**Comment by GajuuzZ** [comment]
Yes, you can. But you have to train new action recognition model cause you can't use my pre-train since it trained for 30 frames.

**Comment by GajuuzZ** [comment]
You can make your own data loader just make it return in the shape I note in the train.py file. or if you want to know which process I used you can see it in the Data folder.

**Comment by FreedoomG** [comment]
Thx and I'll read them later!
