### ISSUE TITLE
the performance of using resnet50 ia better than resnet101

### ISSUE THREAD

**Issue by FreedoomG** [GajuuzZ/Human-Falling-Detect-Tracks#54]
when I test the performance by using the same datasets as the demo, I found that the performance of using resnet50 as the pose backbone and the confidence of the action prediction is better than that of using resnet101.
Could you give some suggestion why it happened?

There's my thinking:
1. by using resnet101, the poses are not fully detected and cannot be feed into the action estimate model as its demand.
2. the 30 frames of keypoints of the input of the action estimate model should fulfil some restrictions. If so, could you provide these?

**Comment by GajuuzZ** [comment]
What dataset did you use. And how did you evaluate. Can you show me the sample?

**Comment by FreedoomG** [comment]
1. The datasets is from https://imvia.u-bourgogne.fr/en/database/fall-detection-dataset-2.html which is the same as the demo you posed in this project
2. I just evaluate in a simple way by traverse all the videos in the datasets such as Home_01 and Home_02 and watch the performances.

There are the performances of the using resnet101 and resnet50 with other parameters didn't change to evaluate the Home_01/video (16).avi.
you can see when the man falls down, the detection bbox lose but the tracker bbox keep finding the keypoints and stay at the right place.
I was doubtful that resnet50 find the keypoints more often with low confidence while resnet101 cannot find the keypoints cuz the confidence was lower than the threshold?

1)detection_input_size = 384
pose_input_size = 320x256
pose_backbone = resnet50

https://user-images.githubusercontent.com/43680385/134269737-2a30e28d-a45d-407c-907d-80cea7d8602b.mp4

 2)detection_input_size =384
pose_input_size = 320x256
pose_backbone = resnet101

https://user-images.githubusercontent.com/43680385/134269758-c34da8af-d30b-42d6-9284-1e12dfbc3158.mp4

**Comment by GajuuzZ** [comment]
I use 2 sources of the detection boxes from the YOLO and Kalman filter. When YOLO can't detect it start to use predictions from Kalman. These boxes feed into the pose model and return results with enough confidence threshold. Then use the box from the pose result to update the Kalman. So when the pose model can't get enough confidence it returns none for that track make the Kalman keep going on the flow. 

So First, these models are base on average you can't say one is better than another by a few samples. you need to evaluate the whole dataset. Cause they are still a chance that some models can perform worse than the smaller ones on some samples but it may have a better average result. As you saw even the resnet50 returns the result but it has very low confidence make the pose look messy that doesn't mean it performs better it could call False Positive cause it missed the actual points.

**Comment by FreedoomG** [comment]
Thx for the explanation and using Kalman filter is really a good idea to track the target for its lower computational expense!
