### ISSUE TITLE
ModuleNotFoundError: No module named 'Visualizer'

### ISSUE THREAD

**Issue by Brianxq** [GajuuzZ/Human-Falling-Detect-Tracks#9]
from Visualizer import plot_graphs, plot_confusion_metrix
ModuleNotFoundError: No module named 'Visualizer'

**Comment by 17702513221** [comment]
pip3 install Visualizer
bu the error is stail

**Comment by GajuuzZ** [comment]
Visualizer is just a ploting module. I didn't upload to the git. But it not necessarily for training you can comment it and it associated lines or write ploting by yourself.
