### ISSUE TITLE
Pretrain drive Access is not available.

### ISSUE THREAD

**Issue by ibtehajali67** [GajuuzZ/Human-Falling-Detect-Tracks#96]
Can you please share pretrain weights

**Comment by talentjls** [comment]
Can you please share pretrain weights，This is my email：jialesong56@gmail.com
@GajuuzZ

**Comment by AntonioZheng** [comment]
Can you please share pretrain weights，This is my email：1352831592@qq.com
@GajuuzZ

**Comment by sankamohotttala** [comment]
refer #99

**Comment by ibtehajali67** [comment]
> refer #99

Thank you @sankamohotttala
